### ISSUE TITLE
Trouble uploading audience to GoogleAds

### ISSUE THREAD

**Issue by BiancaK3** [google/megalista#58]
I'm trying to send audience lists to Google Ads, but having the following error in all forms of Customer Match:

`ERROR:megalista.GoogleAdsCustomerMatchAbstractUploader:'int' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/utils.py", line 72, in inner
    return func(*args, **kwargs)
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 209, in process
    execution.destination.destination_metadata))
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 60, in _create_list_if_it_does_not_exist
    customer_id, list_name, list_definition)
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 70, in _do_create_list_if_it_does_not_exist
    resource_name = self._get_user_list_resource_name(customer_id, list_name)
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 109, in _get_user_list_resource_name
    query_aux = f"AND user_list.access_reason={ads_client.enums.AccessReasonEnum.OWNED.name}"
AttributeError: 'int' object has no attribute 'name'
ERROR:megalista.GoogleAdsCustomerMatchAbstractUploader:Error uploading data.
Traceback (most recent call last):
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/utils.py", line 72, in inner
    return func(*args, **kwargs)
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 209, in process
    execution.destination.destination_metadata))
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 60, in _create_list_if_it_does_not_exist
    customer_id, list_name, list_definition)
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 70, in _do_create_list_if_it_does_not_exist
    resource_name = self._get_user_list_resource_name(customer_id, list_name)
  File "/home/bianca_santos/google-marketing-data-sync/megalista-v2/megalista/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py", line 109, in _get_user_list_resource_name
    query_aux = f"AND user_list.access_reason={ads_client.enums.AccessReasonEnum.OWNED.name}"
AttributeError: 'int' object has no attribute 'name'
INFO:megalista.GoogleAdsOfflineUploader:Uploading 1000 rows...
INFO:megalista.GoogleAdsOfflineConversionsUploader:Uploading 1000 offline conversions on customers/5852184472/conversionActions/792598949 to Google Ads.
ERROR:megalista.GoogleAdsOfflineConversionsUploader:Error on uploading offline conversions: Multiple errors in ‘details’. First error: The click or call is owned by a customer account that the uploading customer does not manage., at conversions[0].gclid.
INFO:megalista:Completed successfully!`

The account is a MCC Google Ads Account.

**Comment by antoniolmm** [comment]
Hi Bianca,

Are you on the last commit of the main branch?
Or have you many any modifications to the code?
I'm asking because you error message (`query_aux = f"AND user_list.access_reason={ads_client.enums.AccessReasonEnum.OWNED.name}`) differs from the base source [here](https://github.com/google/megalista/blob/e00937d73ac1404312c280241cffe00e89e93892/megalista_dataflow/uploaders/google_ads/customer_match/abstract_uploader.py#L103).

**Comment by BiancaK3** [comment]
Hello, 

Yes, I did that because while debugging I found out that the error in the source code was misleading. But I found out that the issue was the Python version, I was using the newer one. 
So I saw that there's a pull request for megalista to work in this Python version and using that code the problem was solved. 

Thank you for your input anyway!
